version: '3'
services:
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres:13.0-alpine
    environment:
      POSTGRES_PASSWORD: tunkkitunkki
      POSTGRES_DB: tunkkidb
      POSTGRES_USER: tunkkibois
    volumes:
      - ./database-data:/var/lib/postgresql/data/
      - ./sql/combined.sql:/docker-entrypoint-initdb.d/init.sql
  front:
    build: ./front
    ports:
      - 3000:3000
    volumes:
      - ./front/src:/client/src
  back:
    build: ./back
    ports:
      - 3001:3001 
    volumes:
      - ./back/src:/back/src
  
  infopage:
    build: ./infopage
    ports:
      - 5000:5000
  
  nginx-proxy:
    image: staticfloat/nginx-certbot
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./conf.d:/etc/nginx/user.conf.d:ro
      - letsencrypt:/etc/letsencrypt
    environment:
      CERTBOT_EMAIL: jaan.taponen@aalto.fi
    depends_on:
     - front


volumes:
  letsencrypt:

networks:
  default:
    name: servu
    driver: bridge
