version: '3'
services:
  adminer:
    image: adminer
    depends_on:
      - postgres
    ports:
      - 8080:8080
  postgres:
    image: postgres # use latest official postgres version
    ports:
      - 8081:5432
    environment:
      POSTGRES_PASSWORD: tunkkitunkki
      POSTGRES_DB: tunkkidb
      POSTGRES_USER: tunkkibois
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./sql/table_structure.sql:/docker-entrypoint-initdb.d/init.sql
  front:
    build: ./front
    ports:
      - 80:3000
  back:
    build: ./back
    ports:
      - 8082:3000

volumes:
  database-data: